AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack taller lambda 01

Parameters:
  team:
    Description: "name team"
    Type: String
  environment:
    Description: "name envoriment"
    Type: String
  application:
    Description: "name Application"
    Type: String
  stack:
    Description: "name Stack"
    Type: String    
  
Resources:
  LambdaDemo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      FunctionName:
        !Sub "ibk-${team}-${application}-${stack}-${environment}-lambda-Sam"
      Description: "Lambda taller01"
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt rRoleLambdaExecution.Arn
  
  rRoleLambdaExecution:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "ibk-${team}-${application}-${stack}-${environment}-execute-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "rpa-${team}-${application}-${stack}-${environment}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogGroupPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "*"
                
              - Sid: S3Policy
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub "arn:aws:s3:::account-juan-result-${environment}"
                  - !Sub "arn:aws:s3:::account-juan-result-${environment}/*"
              
                
#Outputs:
#  lambda:
#    Value: !GetAtt Function.Arn