AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack taller lambda 01

Parameters:
  team:
    Description: "name team"
    Type: String
  environment:
    Description: "name envoriment"
    Type: String
  application:
    Description: "name Application"
    Type: String
  stack:
    Description: "name Stack"
    Type: String    
  
Resources:
  FunctionCF:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./src
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      FunctionName:
        !Sub "rpa-${team}-${application}-${stack}-${environment}-lambda-cf"
      Description: Python Function to return specific TimeZone time
      MemorySize: 128
      Timeout: 3
      Role: !GetAtt rRoleLambdaExecution.Arn
  
  #FunctionSam:
  #  Type: AWS::Serverless::Function
  #  Properties:
  #    CodeUri: ./src
  #    Handler: lambda_function.lambda_handler
  #    Runtime: python3.7
  #    FunctionName:
  #      !Sub "ibk-${team}-${application}-${stack}-${environment}-lambda-Sam"
  #    Description: "Lambda taller01"
  #    MemorySize: 128
  #    Timeout: 3
  #    #Role: !GetAtt rRoleLambdaExecution.Arn        
  
  #FunctionLogGroup:
  #  Type: "AWS::Logs::LogGroup"
  #  Properties:
  #    LogGroupName: !Join
  #      - ""
  #      - - /aws/lambda/
  #        - !Sub "ibk-${team}-${application}-${stack}-${environment}-lambda"

  rRoleLambdaExecution:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "ibk-${team}-${application}-${stack}-${environment}-execute-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "rpa-${team}-${application}-${stack}-${environment}-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogGroupPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:us-east-1:433029499227:log-group:/aws/lambda/ibk-rpa-taller01-lambda-dev-lambda-cf:*"
                
#Outputs:
#  lambda:
#    Value: !GetAtt Function.Arn