AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for layers

Parameters:  
  environment:
    Description: "name envoriment"
    Type: String
  application:
    Description: "name Application"
    Type: String
  stack:
    Description: "name Stack"
    Type: String        
  team:
    Description: "name team"
    Type: String  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Resources:
  LambdaLayerCommon:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      ContentUri: ../layers/
      Description: Common Layer Stack
      LayerName: !Sub "${team}-${stack}-${application}-commom-layer"

Outputs:
  oLayerCommom:
      Description: "layer de librerias common"
      Value: !Ref LambdaLayerCommon        